# Daytimer Configuration File

# Set the full path to the default text editor you'd like to use.
# You can also set $EDITOR in the environment. Otherwise will try to find a
# default editor to use.
editor: ""

# Add the SMTP configuration to send email agendas (e.g. Amazon SES or
# Google Mail). Note that from must be a valid email address and will be
# used as the sender of the email with the name "Daytimer Agenda".
email:
  from: ""
  host: "smtp.gmail.com"
  port: 587
  user: ""
  password: ""
  use_tls: true
